### PR TITLE
Fix windows build and bump resolver version to the latest LTS-13.28 (ghc 8.6.5)

### PR DESCRIPTION
**Pull request by arvindd**
Attention: @stites 

## Description
**Windows build**
The stack.yaml file contained linux library paths for extra-libs. This was causing build errors in Windows. Hence, commented out the lines.

**Bumped stack resolver version to LTS-13.28 (ghc 8.6.5)**
To bring it to the latest (as of today) stable stack resolver.

By bringing this to the latest version, the build failed due to a non-exhaustive-pattern match (because ghc 8.6.5 checks more exhaustive). 

This error was also fixed so that the package builds with the latest resolver.

## Motivation and Context
See above.

## How Has This Been Tested?
Built the same both on Windows and Linux.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project -- in essence, you've run the brittany formatter over your code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by stites** [comment]
Pending CI, this looks fine to me -- @xnomagichash, what is the status of this repo? Is someone at Sentenai going to have time to take over maintenance?

**Comment by arvindd** [comment]
@stites:
The CI has failed, unfortunately :-( But looks like this is due to a bad .travis.yml file: and that possibly needs another PR. Travis builds with this line: stack... reinforce-prelude, and this package is not in the current code-base (it was not there even before this PR, so obviously the CI had failed even before this PR).

I shall also fix that problem in the travis file once this PR is merged - so that will be my next PR.

**Comment by stites** [comment]
> I shall also fix that problem in the travis file once this PR is merged - so that will be my next PR.

I just removed the offending line directly and re-triggered CI.

**Comment by stites** [comment]
Okay, I've built this on my machine and it is working as expected. Retriggering the build does not actually update where it is merging into master, so `travis.yml` remains unchanged. I would be happy to merge this but it feels a bit odd to merge without someone at @Sentenai for the final go-ahead.

The updated `.travis.yml` also fails on master due to some hlint suggestions (see https://travis-ci.org/Sentenai/reinforce/builds/561082616#L5880 ) in retrospect `weeder` and `hlint` in CI is a bit overkill for this project. @arvindd I think a good followup PR would make the call on removing or appeasing these.

**Comment by arvindd** [comment]
Ok @stites, will raise another followup PR to solve the Travis errors after this PR is merged.

**Comment by arvindd** [comment]
@xnomagichash: I decided to go raise this PR as I noticed that the repo had been stuck with a very old ghc / resolver, and I wanted to further this development.

Kindly merge this PR, and also drop a line on the roadmap/possibility of a handover of maintenance to somebody (including me). I can try to at least keep this afloat by accepting PRs and also furthering development / creating roadmap, of course, with the help of @stites and others who have been overseeing this development before. 

If you choose to handover to me, I shall continue the maintenance in arvindd/reinforce/master and not in this repo, or even possibly move this repo under the DataHaskell project, subject to acceptance of that project.

**Comment by stites** [comment]
Okay, I think @xnomagichash might be a bit busy. Since I know that things are pinned correctly, I'm going to go ahead and merge this, but it would be good to get some feedback from someone at Sentenai.

Pinging some folks in case Brendan is tied up: @xilnocas, @meangrape, @brandly, @seagreen.

**Comment by xnomagichash** [comment]
Sorry got a little busy here. We'll discuss about who should take over maintainership.

**Pull request merged**
